export const BOARD_EMIT_EVENT = {
  JOIN_BOARD: 'JOIN_BOARD',
  LEAVE_BOARD: 'LEAVE_BOARD',
};

export const LIST_SUBSCRIBE_EVENT = {
  CREATED_LIST: 'CREATED_LIST',
  UPDATED_LIST: 'UPDATED_LIST',
  CONNECT: 'connect',
};

export const CARD_SUBSCRIBE_EVENT = {
  NEW_CARD_ADDED: 'NEW_CARD_ADDED',
  UPDATED_CARD_ORDER: 'UPDATED_CARD_ORDER',
};
